### ISSUE TITLE
What are the differences between the built-in sample texts "BBC News" and "Bibliometrix"?

### ISSUE THREAD

**Issue by fishfree** [massimoaria/tall#94]
"BBC News" can only support such simple functionalities even after I succesfully run the "Tokenization & PoS Tagging" step as the screenshot below:
![image](https://github.com/user-attachments/assets/0f177180-25fd-4b2a-a799-d444091496d6)

"Bibliometrix" can support much more functionalities as the screenshot below:
![image](https://github.com/user-attachments/assets/441f7800-0ed1-4a3f-9ef6-492bdb117696)

I can download an Excel file for "BBC News" as the screenshot below:
![image](https://github.com/user-attachments/assets/1488a320-da80-48bf-afa7-1ec71f7e6faf)
But the same operation against the "Bibliometrix" can only download an empty Excel file.

**Comment by fishfree** [comment]
It seems if [this issue](https://github.com/massimoaria/tall/issues/96) is solved and the step is run, then the more functionalities appear up.

**Comment by massimoaria** [comment]
This is not an issue.
Tall menus appear step by step along the workflow. 
To see analysis menus, a collection has to be tokenized and lemmatized.
 
Bibliometrix is an already tokenized collection, so when you load it all menus are visible!
On the contrary, BBC contains original corpora that have yet to be tokenized. Only edit and pre-processing menus will be visible. After pre-processing all other menus will became visible.
